name: animeclient
description: A cozy anime client
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2

  # Networking
  http: ^1.2.0

  # State Management
  provider: ^6.1.1

  # UI & Animations
  flutter_animate: ^4.5.0
  google_fonts: ^7.0.0
  cached_network_image: ^3.3.1
  lucide_icons: ^0.257.0
  glass_kit: ^4.0.2
  url_launcher: ^6.2.0
  media_kit: ^1.1.10
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.4 # Contains the MPV binaries
  flutter_markdown: ^0.6.14

  # Permissions (for Android/iOS)
  permission_handler: ^12.0.1
  path_provider: ^2.1.1
  open_file: ^3.5.11
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

